{% set version = "1.2.7" %}

package:
  name: r-gribr
  version: {{ version }}

source:
  url: https://github.com/nawendt/gribr/archive/v{{ version }}.tar.gz
  sha256: 6fa045cb7a0422c193c799f3462af876116b3e29320df65c2e40bcf78f7ebb1a

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - r-base
    - r-proj4
    - eccodes >=2.19.0
  run:
    - r-base
    - r-proj4
    - eccodes >=2.19.0

test:
  commands:
    - $R -e "library('gribr')"  # [not win]

about:
  home: http://github.com/nawendt/gribr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R interface for GRIB files using ECMWF ecCodes.
  description: |
    Easily read GRIB data into native R data types.
  dev_url: https://github.com/nawendt/gribr

extra:
  recipe-maintainers:
    - conda-forge/r
    - nawendt
