{% set version = "1.2.6" %}

package:
  name: r-gribr
  version: {{ version }}

source:
  url: https://github.com/nawendt/gribr/archive/v{{ version }}.tar.gz
  sha256: 630e660d9c8391d0da5c0ec510d2f27611350f9ab60ac9fc4a85add1f1c7a8fc

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - pkg-config
  host:
    - r-base
    - r-proj4
    - eccodes >=2.19.0
  run:
    - r-base
    - r-proj4
    - eccodes >=2.19.0

test:
  commands:
    - $R -e "library('gribr')"  # [not win]

about:
  home: http://github.com/nawendt/gribr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R interface for GRIB files using ECMWF ecCodes.
  description: |
    Easily read GRIB data into native R data types.
  dev_url: https://github.com/nawendt/gribr

extra:
  recipe-maintainers:
    - conda-forge/r
    - nawendt
