{% set version = "1.2.3" %}

package:
  name: r-gribr
  version: {{ version }}

source:
  url: https://github.com/nawendt/gribr/archive/v{{ version }}.tar.gz
  sha256: 45cc29a488d8440aea479433ea6b1a29ef24b58988671db6903675a3e1c86943

build:
  number: 6
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - pkg-config
  host:
    - r-base
    - r-proj4
    - proj
    - eccodes >=2.19.0
  run:
    - r-base
    - r-proj4
    - proj
    - eccodes >=2.19.0

test:
  commands:
    - $R -e "library('gribr')"  # [not win]

about:
  home: http://github.com/nawendt/gribr
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R interface for GRIB files using ECMWF ecCodes.
  description: |
    Easily read GRIB data into native R data types.
  dev_url: https://github.com/nawendt/gribr

extra:
  recipe-maintainers:
    - nawendt
