{% set version = "1.2.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gribr
  version: {{ version }}

source:
  url: https://github.com/nawendt/gribr/archive/v{{ version }}.tar.gz
  sha256: 6fa045cb7a0422c193c799f3462af876116b3e29320df65c2e40bcf78f7ebb1a

build:
  number: 2
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - {{ posix }}tar               # [win]
    - {{ posix }}gzip              # [win]
  host:
    - r-base
    - r-proj4
    - eccodes >=2.19.0
  run:
    - r-base
    - r-proj4
    - eccodes >=2.19.0

test:
  commands:
    - $R -e "library('gribr')"           # [not win]
    - "\"%R%\" -e \"library('gribr')\""  # [win]

about:
  home: http://github.com/nawendt/gribr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R interface for GRIB files using ECMWF ecCodes.
  description: |
    Easily read GRIB data into native R data types.
  dev_url: https://github.com/nawendt/gribr

extra:
  recipe-maintainers:
    - conda-forge/r
    - nawendt
