{% set version = "1.2.4" %}

package:
  name: r-gribr
  version: {{ version }}

source:
  url: https://github.com/nawendt/gribr/archive/v{{ version }}.tar.gz
  sha256: b7ea2956b6e94787539958eff2c8cf36e2ba55f8368d77f5180ee683a57878c2

build:
  number: 2
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - pkg-config
  host:
    - r-base
    - r-proj4
    - proj
    - eccodes >=2.19.0
  run:
    - r-base
    - r-proj4
    - proj
    - eccodes >=2.19.0

test:
  commands:
    - $R -e "library('gribr')"  # [not win]

about:
  home: http://github.com/nawendt/gribr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: R interface for GRIB files using ECMWF ecCodes.
  description: |
    Easily read GRIB data into native R data types.
  dev_url: https://github.com/nawendt/gribr

extra:
  recipe-maintainers:
    - nawendt
