{% set version = "1.2.2" %}

package:
  name: r-gribr
  version: {{ version }}

source:
  url: https://github.com/nawendt/gribr/archive/v{{ version }}.tar.gz
  sha256: cc3cb3b0e34a120adf5229e4889366697002bc8f37ebb1a2c7734c2acc559616

build:
  number: 1011
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - pkg-config
  host:
    - r-base
    - r-proj4
    - proj
    - eccodes >=2.0.0
  run:
    - r-base
    - r-proj4
    - proj
    - eccodes >=2.0.0

test:
  commands:
    - $R -e "library('gribr')"  # [not win]

about:
  home: http://github.com/nawendt/gribr
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'R interface for GRIB files using ECMWF ecCodes.'
  description: |
    Easily read GRIB data into native R data types.
  dev_url: https://github.com/nawendt/gribr

extra:
  recipe-maintainers:
    - nawendt
