appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LofuMm6TUOTBR5ufgMWJtMmRoHwnpXo/WlkBuNvHbTlANRO4ImJZvueUigccsAq1D9ONBIHJ/oGQTV7NsG8jEkX1kCAs7RUc2QXuhE+oAAuFTRyvuqvqEU1+1TvLGZgl7JCd/yFf6IP2p16bmMZbQlwWB57sVLRZytiV6igzsoanKTaelsSe944uijA71bvNOHTXrNJoMKfqO1WoK/oKrbHoUf4dMYgoanZnicmWXTWxCl7b5jAIgN4uw8K0P4pyBmBKK3Qj2QD+m2IH+weYShL9UdDXc4VbKSJPAlv6qw9SzXIPlHxLeeMyM9jObn/2JakZEo38peT0h0j+7O4vhHohY2UHjHLJmglKcOHJn9K9VTKSzACHkjQWrbN9Zh+xbJ+BJS+E4qx80DcobmCU54lUyYONZHddTx3vKpYt6Z9Pk3m7e07/fH4tO2L6ylGeCQLXSVaYYs2gHQjYMfh7ZVLiR8lJO9BBW9N4F50AySR+/osF+6L8hCxCaalQ0tWggLNCMYe6ibvdAY0BW8DaBkgKZ4ZCP/TQIVNrexjt+9YnRV/hZo5Ev6TeZiqJkuo1fb3rWaxiPR578/GL223+cIm3CZpahvN/9Cijs+sqVz0EJHjnn8Y/+BeR37Hoj5NK/8YNzGJqh0ikVjfrFjopPu1Lr+POQUw0UFfx+iE8Qj0=
conda_forge_output_validation: true
