travis:
  secure:
    BINSTAR_TOKEN: s3ifgZxqGUhxvNcalhkQK191eaYxmgAPGs0lxbII6Fcwy24LUWRk1qMGFIu4syhrPTcac38vH/QmhMKKl0XZAhvIPm4pocm5jhKh1pgcTnHofvcUhs1xCevZT8YRL5R3DvFq1Vjayrt544ieRiGs6ogYMaBqL4M4AjEK5GQu/Xsz5tQpHKEhgoRCdtEXq80pglkdnJFuElu8W4wGRWm4HywZW65AYonLRh3CpLuCvWfaWdB1u1WB2h50QNvxTfK2YeJb0PGzuXgvP+ruuLlNdkxfm4u9r4XznaoZ5xVQdkstQLPkH88cG6lskRdij9zLnpVmG51qmMju6+iaZ3FmDNf2CVbu+Iv7TSeOmMXnZKrPU7IB0eJ+6UdLZw9CLoiBRW7W3AXB2dKI+V5if0j5UAFaYh7L4cm9/XV8ky2nDIBI3vfn2Ll5GzswZ7IY6rjWg8i4GmiO3vykZ4eikRWLSe6l25ZoqopLJG6iNbAVpk/jbrV2QxQ3IPvka4G4bz2JKptn4EGE00rZUVNtVja2FPWoXPLVCa6YW+1TxbES4vkNE05hFwmnEzrklziPOau4qQWfYvQ1NF3ijdxp3W+Ro6bH70hrY8V6LaEYpY7qiYGj9XvzQQU9gpMmRV6Ki0TjvoxnJEXl2I9XAoJWwOBIkWKwBSRxJsQZ0MnQMcQVmaM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
